# steemit-overseer default configuration, override in your config/local-development.toml

# port to listen on
port = 8090

# whether the app runs behind a trusted proxy
proxy = false

# application name used for logging and rpc namespacing
name = 'overseer'

# number of worker processes to spawn, 0 = autodetect
num_workers = 1

# logging output, can be repeated
[[log]]
level = 'debug'
out = 'stdout' # path or stdout/err

# rakam client settings
# [rakam]
# api_endpoint = 'my.rakam.server'
# api_key = 'rakam-api-write-key'
